### ISSUE TITLE
tf-serving output on AWS is excessive

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-tf-serving#8] opened 2018-11-19 20:47 UTC
It would be nice to find a solution to this. Is there an issue for this on the tensorflow/serving?

See attached image for an example (note the timestamps):
![tf-serving_aws_verbose_output](https://user-images.githubusercontent.com/21188071/48734084-3f870f00-ebf9-11e8-8bcc-81894b34dcac.png)

**Comment by willgraf** [comment] 2018-11-21 23:03
This looks like a duplicate of https://github.com/tensorflow/serving/issues/789

**Comment by willgraf** [comment] 2018-12-19 16:31
Someone in that thread found

> Sorry we found that the missing S3 permissions fixed the problem: `"s3:DeleteObject"`

Maybe adding this to our service account will help stifle some of the logging?  Not sure what it is trying to delete though...

**Comment by orf** [comment] 2018-12-19 16:33
Hmm, I used a service account with full admin permissions, I really don't think it's that :(

**Comment by eggie5** [comment] 2019-04-18 18:47
This issue is independent of TF Serving, it is an issue w/ TF. Using TF w/ S3 bindings spams the logs...

**Comment by eggie5** [comment] 2019-04-18 19:28
make sure you set undocumented  `AWS_LOG_LEVEL` env var or else the TF s3 plugin will spam your logs, eg: `export AWS_LOG_LEVEL=3`  for `FATAL`

**Closed** 2019-05-03 00:44 UTC
Labels: enhancement
